/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthVisaoGeralImport } from './routes/_auth/visao-geral'
import { Route as AuthProjetosImport } from './routes/_auth/projetos'
import { Route as AuthHomeImport } from './routes/_auth/home'
import { Route as AuthConfiguracoesImport } from './routes/_auth/configuracoes'
import { Route as AuthAtualizacoesImport } from './routes/_auth/atualizacoes'
import { Route as AuthAgendaImport } from './routes/_auth/agenda'
import { Route as AuthProjetoImport } from './routes/_auth/_projeto'
import { Route as AuthFinanceiroIndexImport } from './routes/_auth/financeiro/index'
import { Route as AuthDocumentosIndexImport } from './routes/_auth/documentos/index'
import { Route as AuthProjetoSlugImport } from './routes/_auth/_projeto/$slug'
import { Route as AuthDocumentosFolderSlugIndexImport } from './routes/_auth/documentos/$folderSlug/index'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVisaoGeralRoute = AuthVisaoGeralImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProjetosRoute = AuthProjetosImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHomeRoute = AuthHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)

const AuthConfiguracoesRoute = AuthConfiguracoesImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAtualizacoesRoute = AuthAtualizacoesImport.update({
  id: '/atualizacoes',
  path: '/atualizacoes',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAgendaRoute = AuthAgendaImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProjetoRoute = AuthProjetoImport.update({
  id: '/_projeto',
  getParentRoute: () => AuthRoute,
} as any)

const AuthFinanceiroIndexRoute = AuthFinanceiroIndexImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDocumentosIndexRoute = AuthDocumentosIndexImport.update({
  id: '/documentos/',
  path: '/documentos/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProjetoSlugRoute = AuthProjetoSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthProjetoRoute,
} as any)

const AuthDocumentosFolderSlugIndexRoute =
  AuthDocumentosFolderSlugIndexImport.update({
    id: '/documentos/$folderSlug/',
    path: '/documentos/$folderSlug/',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_projeto': {
      id: '/_auth/_projeto'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthProjetoImport
      parentRoute: typeof AuthImport
    }
    '/_auth/agenda': {
      id: '/_auth/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthAgendaImport
      parentRoute: typeof AuthImport
    }
    '/_auth/atualizacoes': {
      id: '/_auth/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AuthAtualizacoesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/configuracoes': {
      id: '/_auth/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthConfiguracoesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeImport
      parentRoute: typeof AuthImport
    }
    '/_auth/projetos': {
      id: '/_auth/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthProjetosImport
      parentRoute: typeof AuthImport
    }
    '/_auth/visao-geral': {
      id: '/_auth/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthVisaoGeralImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_projeto/$slug': {
      id: '/_auth/_projeto/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthProjetoSlugImport
      parentRoute: typeof AuthProjetoImport
    }
    '/_auth/documentos/': {
      id: '/_auth/documentos/'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthDocumentosIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/financeiro/': {
      id: '/_auth/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthFinanceiroIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/documentos/$folderSlug/': {
      id: '/_auth/documentos/$folderSlug/'
      path: '/documentos/$folderSlug'
      fullPath: '/documentos/$folderSlug'
      preLoaderRoute: typeof AuthDocumentosFolderSlugIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthProjetoRouteChildren {
  AuthProjetoSlugRoute: typeof AuthProjetoSlugRoute
}

const AuthProjetoRouteChildren: AuthProjetoRouteChildren = {
  AuthProjetoSlugRoute: AuthProjetoSlugRoute,
}

const AuthProjetoRouteWithChildren = AuthProjetoRoute._addFileChildren(
  AuthProjetoRouteChildren,
)

interface AuthRouteChildren {
  AuthProjetoRoute: typeof AuthProjetoRouteWithChildren
  AuthAgendaRoute: typeof AuthAgendaRoute
  AuthAtualizacoesRoute: typeof AuthAtualizacoesRoute
  AuthConfiguracoesRoute: typeof AuthConfiguracoesRoute
  AuthHomeRoute: typeof AuthHomeRoute
  AuthProjetosRoute: typeof AuthProjetosRoute
  AuthVisaoGeralRoute: typeof AuthVisaoGeralRoute
  AuthDocumentosIndexRoute: typeof AuthDocumentosIndexRoute
  AuthFinanceiroIndexRoute: typeof AuthFinanceiroIndexRoute
  AuthDocumentosFolderSlugIndexRoute: typeof AuthDocumentosFolderSlugIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProjetoRoute: AuthProjetoRouteWithChildren,
  AuthAgendaRoute: AuthAgendaRoute,
  AuthAtualizacoesRoute: AuthAtualizacoesRoute,
  AuthConfiguracoesRoute: AuthConfiguracoesRoute,
  AuthHomeRoute: AuthHomeRoute,
  AuthProjetosRoute: AuthProjetosRoute,
  AuthVisaoGeralRoute: AuthVisaoGeralRoute,
  AuthDocumentosIndexRoute: AuthDocumentosIndexRoute,
  AuthFinanceiroIndexRoute: AuthFinanceiroIndexRoute,
  AuthDocumentosFolderSlugIndexRoute: AuthDocumentosFolderSlugIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthProjetoRouteWithChildren
  '/agenda': typeof AuthAgendaRoute
  '/atualizacoes': typeof AuthAtualizacoesRoute
  '/configuracoes': typeof AuthConfiguracoesRoute
  '/home': typeof AuthHomeRoute
  '/projetos': typeof AuthProjetosRoute
  '/visao-geral': typeof AuthVisaoGeralRoute
  '/$slug': typeof AuthProjetoSlugRoute
  '/documentos': typeof AuthDocumentosIndexRoute
  '/financeiro': typeof AuthFinanceiroIndexRoute
  '/documentos/$folderSlug': typeof AuthDocumentosFolderSlugIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthProjetoRouteWithChildren
  '/agenda': typeof AuthAgendaRoute
  '/atualizacoes': typeof AuthAtualizacoesRoute
  '/configuracoes': typeof AuthConfiguracoesRoute
  '/home': typeof AuthHomeRoute
  '/projetos': typeof AuthProjetosRoute
  '/visao-geral': typeof AuthVisaoGeralRoute
  '/$slug': typeof AuthProjetoSlugRoute
  '/documentos': typeof AuthDocumentosIndexRoute
  '/financeiro': typeof AuthFinanceiroIndexRoute
  '/documentos/$folderSlug': typeof AuthDocumentosFolderSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/_projeto': typeof AuthProjetoRouteWithChildren
  '/_auth/agenda': typeof AuthAgendaRoute
  '/_auth/atualizacoes': typeof AuthAtualizacoesRoute
  '/_auth/configuracoes': typeof AuthConfiguracoesRoute
  '/_auth/home': typeof AuthHomeRoute
  '/_auth/projetos': typeof AuthProjetosRoute
  '/_auth/visao-geral': typeof AuthVisaoGeralRoute
  '/_auth/_projeto/$slug': typeof AuthProjetoSlugRoute
  '/_auth/documentos/': typeof AuthDocumentosIndexRoute
  '/_auth/financeiro/': typeof AuthFinanceiroIndexRoute
  '/_auth/documentos/$folderSlug/': typeof AuthDocumentosFolderSlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/agenda'
    | '/atualizacoes'
    | '/configuracoes'
    | '/home'
    | '/projetos'
    | '/visao-geral'
    | '/$slug'
    | '/documentos'
    | '/financeiro'
    | '/documentos/$folderSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/agenda'
    | '/atualizacoes'
    | '/configuracoes'
    | '/home'
    | '/projetos'
    | '/visao-geral'
    | '/$slug'
    | '/documentos'
    | '/financeiro'
    | '/documentos/$folderSlug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/_projeto'
    | '/_auth/agenda'
    | '/_auth/atualizacoes'
    | '/_auth/configuracoes'
    | '/_auth/home'
    | '/_auth/projetos'
    | '/_auth/visao-geral'
    | '/_auth/_projeto/$slug'
    | '/_auth/documentos/'
    | '/_auth/financeiro/'
    | '/_auth/documentos/$folderSlug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_projeto",
        "/_auth/agenda",
        "/_auth/atualizacoes",
        "/_auth/configuracoes",
        "/_auth/home",
        "/_auth/projetos",
        "/_auth/visao-geral",
        "/_auth/documentos/",
        "/_auth/financeiro/",
        "/_auth/documentos/$folderSlug/"
      ]
    },
    "/_auth/_projeto": {
      "filePath": "_auth/_projeto.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_projeto/$slug"
      ]
    },
    "/_auth/agenda": {
      "filePath": "_auth/agenda.tsx",
      "parent": "/_auth"
    },
    "/_auth/atualizacoes": {
      "filePath": "_auth/atualizacoes.tsx",
      "parent": "/_auth"
    },
    "/_auth/configuracoes": {
      "filePath": "_auth/configuracoes.tsx",
      "parent": "/_auth"
    },
    "/_auth/home": {
      "filePath": "_auth/home.tsx",
      "parent": "/_auth"
    },
    "/_auth/projetos": {
      "filePath": "_auth/projetos.tsx",
      "parent": "/_auth"
    },
    "/_auth/visao-geral": {
      "filePath": "_auth/visao-geral.tsx",
      "parent": "/_auth"
    },
    "/_auth/_projeto/$slug": {
      "filePath": "_auth/_projeto/$slug.tsx",
      "parent": "/_auth/_projeto"
    },
    "/_auth/documentos/": {
      "filePath": "_auth/documentos/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/financeiro/": {
      "filePath": "_auth/financeiro/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/documentos/$folderSlug/": {
      "filePath": "_auth/documentos/$folderSlug/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
