/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthProjetosImport } from './routes/_auth/projetos'
import { Route as AuthPerfilImport } from './routes/_auth/perfil'
import { Route as AuthAdminUsuariosImport } from './routes/_auth/admin/usuarios'
import { Route as AuthAdminProjetosImport } from './routes/_auth/admin/projetos'
import { Route as AuthProjetoSlugImport } from './routes/_auth/_projeto.$slug'
import { Route as AuthProjetoSlugVisaoGeralImport } from './routes/_auth/_projeto/$slug/visao-geral'
import { Route as AuthProjetoSlugHomeImport } from './routes/_auth/_projeto/$slug/home'
import { Route as AuthProjetoSlugConfiguracoesImport } from './routes/_auth/_projeto/$slug/configuracoes'
import { Route as AuthProjetoSlugAtualizacoesImport } from './routes/_auth/_projeto/$slug/atualizacoes'
import { Route as AuthProjetoSlugAgendaImport } from './routes/_auth/_projeto/$slug/agenda'
import { Route as AuthProjetoSlugFinanceiroIndexImport } from './routes/_auth/_projeto/$slug/financeiro/index'
import { Route as AuthProjetoSlugDocumentosIndexImport } from './routes/_auth/_projeto/$slug/documentos/index'
import { Route as AuthProjetoSlugFinanceiroFolderSlugIndexImport } from './routes/_auth/_projeto/$slug/financeiro/$folderSlug/index'
import { Route as AuthProjetoSlugDocumentosFolderSlugIndexImport } from './routes/_auth/_projeto/$slug/documentos/$folderSlug/index'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthProjetosRoute = AuthProjetosImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthRoute,
} as any)

const AuthPerfilRoute = AuthPerfilImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminUsuariosRoute = AuthAdminUsuariosImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminProjetosRoute = AuthAdminProjetosImport.update({
  id: '/admin/projetos',
  path: '/admin/projetos',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProjetoSlugRoute = AuthProjetoSlugImport.update({
  id: '/_projeto/$slug',
  path: '/$slug',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProjetoSlugVisaoGeralRoute = AuthProjetoSlugVisaoGeralImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthProjetoSlugRoute,
} as any)

const AuthProjetoSlugHomeRoute = AuthProjetoSlugHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthProjetoSlugRoute,
} as any)

const AuthProjetoSlugConfiguracoesRoute =
  AuthProjetoSlugConfiguracoesImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthProjetoSlugRoute,
  } as any)

const AuthProjetoSlugAtualizacoesRoute =
  AuthProjetoSlugAtualizacoesImport.update({
    id: '/atualizacoes',
    path: '/atualizacoes',
    getParentRoute: () => AuthProjetoSlugRoute,
  } as any)

const AuthProjetoSlugAgendaRoute = AuthProjetoSlugAgendaImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthProjetoSlugRoute,
} as any)

const AuthProjetoSlugFinanceiroIndexRoute =
  AuthProjetoSlugFinanceiroIndexImport.update({
    id: '/financeiro/',
    path: '/financeiro/',
    getParentRoute: () => AuthProjetoSlugRoute,
  } as any)

const AuthProjetoSlugDocumentosIndexRoute =
  AuthProjetoSlugDocumentosIndexImport.update({
    id: '/documentos/',
    path: '/documentos/',
    getParentRoute: () => AuthProjetoSlugRoute,
  } as any)

const AuthProjetoSlugFinanceiroFolderSlugIndexRoute =
  AuthProjetoSlugFinanceiroFolderSlugIndexImport.update({
    id: '/financeiro/$folderSlug/',
    path: '/financeiro/$folderSlug/',
    getParentRoute: () => AuthProjetoSlugRoute,
  } as any)

const AuthProjetoSlugDocumentosFolderSlugIndexRoute =
  AuthProjetoSlugDocumentosFolderSlugIndexImport.update({
    id: '/documentos/$folderSlug/',
    path: '/documentos/$folderSlug/',
    getParentRoute: () => AuthProjetoSlugRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/perfil': {
      id: '/_auth/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthPerfilImport
      parentRoute: typeof AuthImport
    }
    '/_auth/projetos': {
      id: '/_auth/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthProjetosImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_projeto/$slug': {
      id: '/_auth/_projeto/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthProjetoSlugImport
      parentRoute: typeof AuthImport
    }
    '/_auth/admin/projetos': {
      id: '/_auth/admin/projetos'
      path: '/admin/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AuthAdminProjetosImport
      parentRoute: typeof AuthImport
    }
    '/_auth/admin/usuarios': {
      id: '/_auth/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthAdminUsuariosImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_projeto/$slug/agenda': {
      id: '/_auth/_projeto/$slug/agenda'
      path: '/agenda'
      fullPath: '/$slug/agenda'
      preLoaderRoute: typeof AuthProjetoSlugAgendaImport
      parentRoute: typeof AuthProjetoSlugImport
    }
    '/_auth/_projeto/$slug/atualizacoes': {
      id: '/_auth/_projeto/$slug/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/$slug/atualizacoes'
      preLoaderRoute: typeof AuthProjetoSlugAtualizacoesImport
      parentRoute: typeof AuthProjetoSlugImport
    }
    '/_auth/_projeto/$slug/configuracoes': {
      id: '/_auth/_projeto/$slug/configuracoes'
      path: '/configuracoes'
      fullPath: '/$slug/configuracoes'
      preLoaderRoute: typeof AuthProjetoSlugConfiguracoesImport
      parentRoute: typeof AuthProjetoSlugImport
    }
    '/_auth/_projeto/$slug/home': {
      id: '/_auth/_projeto/$slug/home'
      path: '/home'
      fullPath: '/$slug/home'
      preLoaderRoute: typeof AuthProjetoSlugHomeImport
      parentRoute: typeof AuthProjetoSlugImport
    }
    '/_auth/_projeto/$slug/visao-geral': {
      id: '/_auth/_projeto/$slug/visao-geral'
      path: '/visao-geral'
      fullPath: '/$slug/visao-geral'
      preLoaderRoute: typeof AuthProjetoSlugVisaoGeralImport
      parentRoute: typeof AuthProjetoSlugImport
    }
    '/_auth/_projeto/$slug/documentos/': {
      id: '/_auth/_projeto/$slug/documentos/'
      path: '/documentos'
      fullPath: '/$slug/documentos'
      preLoaderRoute: typeof AuthProjetoSlugDocumentosIndexImport
      parentRoute: typeof AuthProjetoSlugImport
    }
    '/_auth/_projeto/$slug/financeiro/': {
      id: '/_auth/_projeto/$slug/financeiro/'
      path: '/financeiro'
      fullPath: '/$slug/financeiro'
      preLoaderRoute: typeof AuthProjetoSlugFinanceiroIndexImport
      parentRoute: typeof AuthProjetoSlugImport
    }
    '/_auth/_projeto/$slug/documentos/$folderSlug/': {
      id: '/_auth/_projeto/$slug/documentos/$folderSlug/'
      path: '/documentos/$folderSlug'
      fullPath: '/$slug/documentos/$folderSlug'
      preLoaderRoute: typeof AuthProjetoSlugDocumentosFolderSlugIndexImport
      parentRoute: typeof AuthProjetoSlugImport
    }
    '/_auth/_projeto/$slug/financeiro/$folderSlug/': {
      id: '/_auth/_projeto/$slug/financeiro/$folderSlug/'
      path: '/financeiro/$folderSlug'
      fullPath: '/$slug/financeiro/$folderSlug'
      preLoaderRoute: typeof AuthProjetoSlugFinanceiroFolderSlugIndexImport
      parentRoute: typeof AuthProjetoSlugImport
    }
  }
}

// Create and export the route tree

interface AuthProjetoSlugRouteChildren {
  AuthProjetoSlugAgendaRoute: typeof AuthProjetoSlugAgendaRoute
  AuthProjetoSlugAtualizacoesRoute: typeof AuthProjetoSlugAtualizacoesRoute
  AuthProjetoSlugConfiguracoesRoute: typeof AuthProjetoSlugConfiguracoesRoute
  AuthProjetoSlugHomeRoute: typeof AuthProjetoSlugHomeRoute
  AuthProjetoSlugVisaoGeralRoute: typeof AuthProjetoSlugVisaoGeralRoute
  AuthProjetoSlugDocumentosIndexRoute: typeof AuthProjetoSlugDocumentosIndexRoute
  AuthProjetoSlugFinanceiroIndexRoute: typeof AuthProjetoSlugFinanceiroIndexRoute
  AuthProjetoSlugDocumentosFolderSlugIndexRoute: typeof AuthProjetoSlugDocumentosFolderSlugIndexRoute
  AuthProjetoSlugFinanceiroFolderSlugIndexRoute: typeof AuthProjetoSlugFinanceiroFolderSlugIndexRoute
}

const AuthProjetoSlugRouteChildren: AuthProjetoSlugRouteChildren = {
  AuthProjetoSlugAgendaRoute: AuthProjetoSlugAgendaRoute,
  AuthProjetoSlugAtualizacoesRoute: AuthProjetoSlugAtualizacoesRoute,
  AuthProjetoSlugConfiguracoesRoute: AuthProjetoSlugConfiguracoesRoute,
  AuthProjetoSlugHomeRoute: AuthProjetoSlugHomeRoute,
  AuthProjetoSlugVisaoGeralRoute: AuthProjetoSlugVisaoGeralRoute,
  AuthProjetoSlugDocumentosIndexRoute: AuthProjetoSlugDocumentosIndexRoute,
  AuthProjetoSlugFinanceiroIndexRoute: AuthProjetoSlugFinanceiroIndexRoute,
  AuthProjetoSlugDocumentosFolderSlugIndexRoute:
    AuthProjetoSlugDocumentosFolderSlugIndexRoute,
  AuthProjetoSlugFinanceiroFolderSlugIndexRoute:
    AuthProjetoSlugFinanceiroFolderSlugIndexRoute,
}

const AuthProjetoSlugRouteWithChildren = AuthProjetoSlugRoute._addFileChildren(
  AuthProjetoSlugRouteChildren,
)

interface AuthRouteChildren {
  AuthPerfilRoute: typeof AuthPerfilRoute
  AuthProjetosRoute: typeof AuthProjetosRoute
  AuthProjetoSlugRoute: typeof AuthProjetoSlugRouteWithChildren
  AuthAdminProjetosRoute: typeof AuthAdminProjetosRoute
  AuthAdminUsuariosRoute: typeof AuthAdminUsuariosRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPerfilRoute: AuthPerfilRoute,
  AuthProjetosRoute: AuthProjetosRoute,
  AuthProjetoSlugRoute: AuthProjetoSlugRouteWithChildren,
  AuthAdminProjetosRoute: AuthAdminProjetosRoute,
  AuthAdminUsuariosRoute: AuthAdminUsuariosRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/perfil': typeof AuthPerfilRoute
  '/projetos': typeof AuthProjetosRoute
  '/$slug': typeof AuthProjetoSlugRouteWithChildren
  '/admin/projetos': typeof AuthAdminProjetosRoute
  '/admin/usuarios': typeof AuthAdminUsuariosRoute
  '/$slug/agenda': typeof AuthProjetoSlugAgendaRoute
  '/$slug/atualizacoes': typeof AuthProjetoSlugAtualizacoesRoute
  '/$slug/configuracoes': typeof AuthProjetoSlugConfiguracoesRoute
  '/$slug/home': typeof AuthProjetoSlugHomeRoute
  '/$slug/visao-geral': typeof AuthProjetoSlugVisaoGeralRoute
  '/$slug/documentos': typeof AuthProjetoSlugDocumentosIndexRoute
  '/$slug/financeiro': typeof AuthProjetoSlugFinanceiroIndexRoute
  '/$slug/documentos/$folderSlug': typeof AuthProjetoSlugDocumentosFolderSlugIndexRoute
  '/$slug/financeiro/$folderSlug': typeof AuthProjetoSlugFinanceiroFolderSlugIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/perfil': typeof AuthPerfilRoute
  '/projetos': typeof AuthProjetosRoute
  '/$slug': typeof AuthProjetoSlugRouteWithChildren
  '/admin/projetos': typeof AuthAdminProjetosRoute
  '/admin/usuarios': typeof AuthAdminUsuariosRoute
  '/$slug/agenda': typeof AuthProjetoSlugAgendaRoute
  '/$slug/atualizacoes': typeof AuthProjetoSlugAtualizacoesRoute
  '/$slug/configuracoes': typeof AuthProjetoSlugConfiguracoesRoute
  '/$slug/home': typeof AuthProjetoSlugHomeRoute
  '/$slug/visao-geral': typeof AuthProjetoSlugVisaoGeralRoute
  '/$slug/documentos': typeof AuthProjetoSlugDocumentosIndexRoute
  '/$slug/financeiro': typeof AuthProjetoSlugFinanceiroIndexRoute
  '/$slug/documentos/$folderSlug': typeof AuthProjetoSlugDocumentosFolderSlugIndexRoute
  '/$slug/financeiro/$folderSlug': typeof AuthProjetoSlugFinanceiroFolderSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/perfil': typeof AuthPerfilRoute
  '/_auth/projetos': typeof AuthProjetosRoute
  '/_auth/_projeto/$slug': typeof AuthProjetoSlugRouteWithChildren
  '/_auth/admin/projetos': typeof AuthAdminProjetosRoute
  '/_auth/admin/usuarios': typeof AuthAdminUsuariosRoute
  '/_auth/_projeto/$slug/agenda': typeof AuthProjetoSlugAgendaRoute
  '/_auth/_projeto/$slug/atualizacoes': typeof AuthProjetoSlugAtualizacoesRoute
  '/_auth/_projeto/$slug/configuracoes': typeof AuthProjetoSlugConfiguracoesRoute
  '/_auth/_projeto/$slug/home': typeof AuthProjetoSlugHomeRoute
  '/_auth/_projeto/$slug/visao-geral': typeof AuthProjetoSlugVisaoGeralRoute
  '/_auth/_projeto/$slug/documentos/': typeof AuthProjetoSlugDocumentosIndexRoute
  '/_auth/_projeto/$slug/financeiro/': typeof AuthProjetoSlugFinanceiroIndexRoute
  '/_auth/_projeto/$slug/documentos/$folderSlug/': typeof AuthProjetoSlugDocumentosFolderSlugIndexRoute
  '/_auth/_projeto/$slug/financeiro/$folderSlug/': typeof AuthProjetoSlugFinanceiroFolderSlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/perfil'
    | '/projetos'
    | '/$slug'
    | '/admin/projetos'
    | '/admin/usuarios'
    | '/$slug/agenda'
    | '/$slug/atualizacoes'
    | '/$slug/configuracoes'
    | '/$slug/home'
    | '/$slug/visao-geral'
    | '/$slug/documentos'
    | '/$slug/financeiro'
    | '/$slug/documentos/$folderSlug'
    | '/$slug/financeiro/$folderSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/perfil'
    | '/projetos'
    | '/$slug'
    | '/admin/projetos'
    | '/admin/usuarios'
    | '/$slug/agenda'
    | '/$slug/atualizacoes'
    | '/$slug/configuracoes'
    | '/$slug/home'
    | '/$slug/visao-geral'
    | '/$slug/documentos'
    | '/$slug/financeiro'
    | '/$slug/documentos/$folderSlug'
    | '/$slug/financeiro/$folderSlug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/perfil'
    | '/_auth/projetos'
    | '/_auth/_projeto/$slug'
    | '/_auth/admin/projetos'
    | '/_auth/admin/usuarios'
    | '/_auth/_projeto/$slug/agenda'
    | '/_auth/_projeto/$slug/atualizacoes'
    | '/_auth/_projeto/$slug/configuracoes'
    | '/_auth/_projeto/$slug/home'
    | '/_auth/_projeto/$slug/visao-geral'
    | '/_auth/_projeto/$slug/documentos/'
    | '/_auth/_projeto/$slug/financeiro/'
    | '/_auth/_projeto/$slug/documentos/$folderSlug/'
    | '/_auth/_projeto/$slug/financeiro/$folderSlug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/perfil",
        "/_auth/projetos",
        "/_auth/_projeto/$slug",
        "/_auth/admin/projetos",
        "/_auth/admin/usuarios"
      ]
    },
    "/_auth/perfil": {
      "filePath": "_auth/perfil.tsx",
      "parent": "/_auth"
    },
    "/_auth/projetos": {
      "filePath": "_auth/projetos.tsx",
      "parent": "/_auth"
    },
    "/_auth/_projeto/$slug": {
      "filePath": "_auth/_projeto.$slug.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_projeto/$slug/agenda",
        "/_auth/_projeto/$slug/atualizacoes",
        "/_auth/_projeto/$slug/configuracoes",
        "/_auth/_projeto/$slug/home",
        "/_auth/_projeto/$slug/visao-geral",
        "/_auth/_projeto/$slug/documentos/",
        "/_auth/_projeto/$slug/financeiro/",
        "/_auth/_projeto/$slug/documentos/$folderSlug/",
        "/_auth/_projeto/$slug/financeiro/$folderSlug/"
      ]
    },
    "/_auth/admin/projetos": {
      "filePath": "_auth/admin/projetos.tsx",
      "parent": "/_auth"
    },
    "/_auth/admin/usuarios": {
      "filePath": "_auth/admin/usuarios.tsx",
      "parent": "/_auth"
    },
    "/_auth/_projeto/$slug/agenda": {
      "filePath": "_auth/_projeto/$slug/agenda.tsx",
      "parent": "/_auth/_projeto/$slug"
    },
    "/_auth/_projeto/$slug/atualizacoes": {
      "filePath": "_auth/_projeto/$slug/atualizacoes.tsx",
      "parent": "/_auth/_projeto/$slug"
    },
    "/_auth/_projeto/$slug/configuracoes": {
      "filePath": "_auth/_projeto/$slug/configuracoes.tsx",
      "parent": "/_auth/_projeto/$slug"
    },
    "/_auth/_projeto/$slug/home": {
      "filePath": "_auth/_projeto/$slug/home.tsx",
      "parent": "/_auth/_projeto/$slug"
    },
    "/_auth/_projeto/$slug/visao-geral": {
      "filePath": "_auth/_projeto/$slug/visao-geral.tsx",
      "parent": "/_auth/_projeto/$slug"
    },
    "/_auth/_projeto/$slug/documentos/": {
      "filePath": "_auth/_projeto/$slug/documentos/index.tsx",
      "parent": "/_auth/_projeto/$slug"
    },
    "/_auth/_projeto/$slug/financeiro/": {
      "filePath": "_auth/_projeto/$slug/financeiro/index.tsx",
      "parent": "/_auth/_projeto/$slug"
    },
    "/_auth/_projeto/$slug/documentos/$folderSlug/": {
      "filePath": "_auth/_projeto/$slug/documentos/$folderSlug/index.tsx",
      "parent": "/_auth/_projeto/$slug"
    },
    "/_auth/_projeto/$slug/financeiro/$folderSlug/": {
      "filePath": "_auth/_projeto/$slug/financeiro/$folderSlug/index.tsx",
      "parent": "/_auth/_projeto/$slug"
    }
  }
}
ROUTE_MANIFEST_END */
